[2024-02-26T18:56:32.964+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [queued]>
[2024-02-26T18:56:32.972+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [queued]>
[2024-02-26T18:56:32.972+0700] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2024-02-26T18:56:32.984+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 11:20:29.138176+00:00
[2024-02-26T18:56:32.986+0700] {standard_task_runner.py:60} INFO - Started process 36447 to run task
[2024-02-26T18:56:32.989+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T11:20:29.138176+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpbz4oku2u']
[2024-02-26T18:56:32.991+0700] {standard_task_runner.py:88} INFO - Job 86: Subtask spark_ingestion_to_s3
[2024-02-26T18:56:33.048+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [running]> on host MinhNhut.
[2024-02-26T18:56:33.126+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T11:20:29.138176+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T11:20:29.138176+00:00'
[2024-02-26T18:56:33.126+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T18:56:33.127+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-26T18:56:33.132+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T18:56:35.237+0700] {subprocess.py:93} INFO - 24/02/26 18:56:35 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-26T18:56:35.239+0700] {subprocess.py:93} INFO - 24/02/26 18:56:35 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-26T18:56:46.571+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-26T18:56:47.108+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-26T18:56:47.109+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-26T18:56:47.126+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-26T18:56:47.132+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a494bf71-32f3-41b0-a1e8-2dc1449334bf;1.0
[2024-02-26T18:56:47.133+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:56:47.646+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-26T18:56:47.691+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-26T18:56:47.753+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-26T18:56:47.799+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 643ms :: artifacts dl 24ms
[2024-02-26T18:56:47.800+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-26T18:56:47.800+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-26T18:56:47.800+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-26T18:56:47.801+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-26T18:56:47.801+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:56:47.801+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-26T18:56:47.801+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-26T18:56:47.802+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:56:47.802+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-26T18:56:47.802+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:56:47.808+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-a494bf71-32f3-41b0-a1e8-2dc1449334bf
[2024-02-26T18:56:47.808+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:56:47.817+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/8ms)
[2024-02-26T18:56:48.106+0700] {subprocess.py:93} INFO - 24/02/26 18:56:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-26T18:56:48.306+0700] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-02-26T18:56:48.311+0700] {process_utils.py:131} INFO - Sending 15 to group 36447. PIDs of all processes in the group: [36455, 36456, 36447]
[2024-02-26T18:56:48.311+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 36447
[2024-02-26T18:56:48.311+0700] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-26T18:56:48.312+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-02-26T18:56:48.333+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-26T18:56:48.338+0700] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T112029, start_date=20240226T115632, end_date=20240226T115648
[2024-02-26T18:56:48.359+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task spark_ingestion_to_s3 (Task received SIGTERM signal; 36447)
[2024-02-26T18:56:48.404+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=36455, status='terminated', started='18:56:32') (36455) terminated with exit code None
[2024-02-26T18:56:48.404+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=36447, status='terminated', exitcode=1, started='18:56:32') (36447) terminated with exit code 1
[2024-02-26T18:56:48.404+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=36456, status='terminated', started='18:56:32') (36456) terminated with exit code None
