[2024-02-26T18:23:29.163+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-26T18:23:29.172+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-26T18:23:29.172+0700] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-02-26T18:23:29.188+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:32:23.006143+00:00
[2024-02-26T18:23:29.190+0700] {standard_task_runner.py:60} INFO - Started process 22585 to run task
[2024-02-26T18:23:29.194+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:32:23.006143+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp10wrf1al']
[2024-02-26T18:23:29.196+0700] {standard_task_runner.py:88} INFO - Job 67: Subtask spark_ingestion_to_s3
[2024-02-26T18:23:29.266+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [running]> on host MinhNhut.
[2024-02-26T18:23:29.366+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:32:23.006143+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:32:23.006143+00:00'
[2024-02-26T18:23:29.367+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T18:23:29.368+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-26T18:23:29.374+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T18:23:32.601+0700] {subprocess.py:93} INFO - 24/02/26 18:23:32 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-26T18:23:32.608+0700] {subprocess.py:93} INFO - 24/02/26 18:23:32 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-26T18:23:42.795+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-26T18:23:42.918+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-26T18:23:42.919+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-26T18:23:42.926+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-26T18:23:42.928+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-7e7fb37e-18ef-4135-9606-d5feb6c5c427;1.0
[2024-02-26T18:23:42.929+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:23:43.213+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-26T18:23:43.269+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-26T18:23:43.362+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-26T18:23:43.392+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 451ms :: artifacts dl 13ms
[2024-02-26T18:23:43.393+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-26T18:23:43.393+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-26T18:23:43.394+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-26T18:23:43.394+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-26T18:23:43.397+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:23:43.398+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-26T18:23:43.399+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-26T18:23:43.399+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:23:43.400+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-26T18:23:43.400+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:23:43.407+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-7e7fb37e-18ef-4135-9606-d5feb6c5c427
[2024-02-26T18:23:43.407+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:23:43.418+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/11ms)
[2024-02-26T18:23:43.920+0700] {subprocess.py:93} INFO - 24/02/26 18:23:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-26T18:23:44.422+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-26T18:23:44.422+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-26T18:24:01.125+0700] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                24/02/26 18:24:01 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-02-26T18:24:30.500+0700] {subprocess.py:93} INFO - [Stage 1:>                                                          (0 + 1) / 1]                                                                                24/02/26 18:24:30 ERROR FileFormatWriter: Aborting job ce0e6c4a-8e01-4411-b238-2b674bf30245.
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - org.apache.hadoop.fs.s3a.RemoteFileChangedException: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) `s3a://olistsalesbucket/olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet': File to rename not found on unguarded S3 store: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) on olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=:404 Not Found
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFile(S3AFileSystem.java:4302)
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.access$1200(S3AFileSystem.java:259)
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem$OperationCallbacksImpl.copyFile(S3AFileSystem.java:2084)
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.copySourceAndUpdateTracker(RenameOperation.java:638)
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.renameFileToDest(RenameOperation.java:365)
[2024-02-26T18:24:30.501+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.execute(RenameOperation.java:310)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1999)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:476)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:490)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:405)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:377)
[2024-02-26T18:24:30.502+0700] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetOutputCommitter.commitJob(ParquetOutputCommitter.java:48)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:192)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$writeAndCommit$3(FileFormatWriter.scala:275)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:552)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:275)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
[2024-02-26T18:24:30.503+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2024-02-26T18:24:30.504+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2024-02-26T18:24:30.505+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:792)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-02-26T18:24:30.506+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-26T18:24:30.507+0700] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) on olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=:404 Not Found
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:266)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:119)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFile(S3AFileSystem.java:4284)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	... 65 more
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
[2024-02-26T18:24:30.508+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1367)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$10(S3AFileSystem.java:2545)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:414)
[2024-02-26T18:24:30.509+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:377)
[2024-02-26T18:24:30.510+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2533)
[2024-02-26T18:24:30.510+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$copyFile$28(S3AFileSystem.java:4286)
[2024-02-26T18:24:30.510+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:117)
[2024-02-26T18:24:30.510+0700] {subprocess.py:93} INFO - 	... 66 more
[2024-02-26T18:24:35.412+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-26T18:24:35.412+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 28, in <module>
[2024-02-26T18:24:35.412+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-26T18:24:35.413+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 25, in extract_data
[2024-02-26T18:24:35.413+0700] {subprocess.py:93} INFO -     df.coalesce(1).write.mode("overwrite").parquet("s3a://olistsalesbucket/" + name_file + ".parquet")
[2024-02-26T18:24:35.413+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2024-02-26T18:24:35.413+0700] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 326, in get_return_value
[2024-02-26T18:24:35.414+0700] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2024-02-26T18:24:35.461+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o41.parquet.
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - : org.apache.hadoop.fs.s3a.RemoteFileChangedException: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) `s3a://olistsalesbucket/olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet': File to rename not found on unguarded S3 store: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) on olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=:404 Not Found
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFile(S3AFileSystem.java:4302)
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.access$1200(S3AFileSystem.java:259)
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem$OperationCallbacksImpl.copyFile(S3AFileSystem.java:2084)
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.copySourceAndUpdateTracker(RenameOperation.java:638)
[2024-02-26T18:24:35.462+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.renameFileToDest(RenameOperation.java:365)
[2024-02-26T18:24:35.463+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.impl.RenameOperation.execute(RenameOperation.java:310)
[2024-02-26T18:24:35.463+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1999)
[2024-02-26T18:24:35.463+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2024-02-26T18:24:35.463+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2024-02-26T18:24:35.463+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2024-02-26T18:24:35.464+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2024-02-26T18:24:35.464+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2024-02-26T18:24:35.464+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:476)
[2024-02-26T18:24:35.464+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:490)
[2024-02-26T18:24:35.464+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:405)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:377)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetOutputCommitter.commitJob(ParquetOutputCommitter.java:48)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:192)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$writeAndCommit$3(FileFormatWriter.scala:275)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:552)
[2024-02-26T18:24:35.465+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:275)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2024-02-26T18:24:35.466+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2024-02-26T18:24:35.467+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2024-02-26T18:24:35.468+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:792)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-02-26T18:24:35.469+0700] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-02-26T18:24:35.470+0700] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-02-26T18:24:35.471+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-26T18:24:35.471+0700] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: copyFile(olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet, olist_order_items_dataset.parquet/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet) on olist_order_items_dataset.parquet/_temporary/0/task_202402261824072312125140619319101_0001_m_000000/part-00000-a18f5149-05a9-455e-9633-8800122102a6-c000.snappy.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=:404 Not Found
[2024-02-26T18:24:35.471+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:266)
[2024-02-26T18:24:35.471+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:119)
[2024-02-26T18:24:35.471+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.copyFile(S3AFileSystem.java:4284)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	... 65 more
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 5KPHG6DG298V4QS5; S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=; Proxy: null), S3 Extended Request ID: gD/bCjJzXF54UouY7/qFgVx6jfws9TSA3Zb0WFb4D7LzaYSIb6STJD1VrLBslR0o/JhL8lOYhV4=
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
[2024-02-26T18:24:35.472+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1367)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$10(S3AFileSystem.java:2545)
[2024-02-26T18:24:35.473+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:414)
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:377)
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2533)
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$copyFile$28(S3AFileSystem.java:4286)
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:117)
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 	... 66 more
[2024-02-26T18:24:35.474+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:24:35.918+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-26T18:24:35.944+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-26T18:24:35.946+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T093223, start_date=20240226T112329, end_date=20240226T112435
[2024-02-26T18:24:35.961+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 22585)
[2024-02-26T18:24:35.971+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T18:24:36.011+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
